# Generated by Django 5.0 on 2023-12-23 03:53

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="red_code",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh1234567890",
                length=10,
                max_length=10,
                prefix="",
                unique=True,
            ),
        ),
    ]
