# Generated by Django 5.0 on 2023-12-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_kyc"),
    ]

    operations = [
        migrations.AddField(
            model_name="kyc",
            name="identity_image",
            field=models.ImageField(blank=True, null=True, upload_to="kyc"),
        ),
    ]
