# Generated by Django 5.0 on 2023-12-25 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_kyc_identity_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="kyc",
            name="account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.account",
            ),
        ),
    ]
